/**
 * This code was generated by Builder.io
 */
import React from "react";

function DifferenceSection() {
  return (
    <section className="flex flex-col mt-12 w-full max-md:mt-10 max-md:max-w-full">
      <h2 className="text-4xl tracking-wide leading-10 text-black text-opacity-90 max-md:max-w-full">
        What's the difference between community and paid version?
      </h2>
      <p className="mt-4 text-base tracking-normal leading-6 text-black text-opacity-60 max-md:max-w-full">
        The community file only includes Material UI instances and not the
        source components. This means that for general purposes, like quickly
        putting together a few screens, it should suffice. However, if you need
        to customize the library, such as changing colors or typography, or
        enabling Dark Mode, you will require the full version with access to the
        components.
      </p>
    </section>
  );
}

export default DifferenceSection;
