/**
 * This code was generated by Builder.io
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex gap-10 justify-between items-start w-full text-xs tracking-wide leading-loose mt-[1279px] text-black text-opacity-40 max-md:mt-10 max-md:max-w-full">
      <div>© mui.com</div>
      <div>MUI for Figma Material UI v6.1.0</div>
    </footer>
  );
}

export default Footer;
