/**
 * This code was generated by Builder.io
 */
import React from "react";

function Header() {
  return (
    <header className="flex overflow-hidden flex-col justify-between p-16 bg-black bg-opacity-10 min-w-[240px] w-[600px] max-md:px-5 max-md:max-w-full">
      <h1 className="flex flex-col w-full text-6xl font-medium tracking-tighter leading-none whitespace-nowrap text-black text-opacity-90 max-md:max-w-full max-md:text-4xl">
        <span className="w-full max-md:max-w-full max-md:text-4xl">
          Welcome
        </span>
      </h1>
      <Footer />
    </header>
  );
}

export default Header;
