/**
 * This code was generated by Builder.io
 */
import React from "react";
import NewFeature from "./NewFeature";
import WelcomeSection from "./WelcomeSection";
import PreviewSection from "./PreviewSection";
import DifferenceSection from "./DifferenceSection";

function MainContent() {
  return (
    <main className="flex flex-col flex-1 shrink self-start p-16 basis-0 min-w-[240px] max-md:px-5 max-md:max-w-full">
      <NewFeature />
      <WelcomeSection />
      <PreviewSection />
      <DifferenceSection />
    </main>
  );
}

export default MainContent;
