/**
 * This code was generated by Builder.io
 */
import React from "react";

function NewFeature() {
  return (
    <section className="flex flex-col w-full max-md:max-w-full">
      <div className="self-start pr-1.5 pl-2 text-xs font-medium tracking-normal leading-loose text-white bg-sky-500 rounded-[100px]">
        New: Variables
      </div>
      <h2 className="mt-4 text-4xl tracking-wide leading-none text-black text-opacity-90 max-md:max-w-full">
        New tokens variables!
      </h2>
      <div className="flex flex-col mt-4 w-full max-md:max-w-full">
        <p className="text-base tracking-normal text-sky-500 max-md:max-w-full">
          <span className="text-black">
            Switching modes can be switched flawlessly with the help of the{" "}
          </span>
          <a
            href="https://help.figma.com/hc/en-us/articles/15343816063383-Modes-for-variables"
            className="text-sky-500"
            target="_blank"
            rel="noopener noreferrer"
          >
            modes for variables
          </a>
          <span className="text-black">.</span>
        </p>
        <div className="flex gap-6 items-start mt-6 w-full max-md:max-w-full">
          <div className="flex flex-col flex-1 shrink justify-center items-start w-full basis-0 min-w-[240px] max-md:max-w-full">
            <div className="flex overflow-hidden flex-col items-end pl-20 w-96 max-w-full rounded border border-solid bg-black bg-opacity-0 border-black border-opacity-10 max-md:pl-5">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/5f631a91ec9b4d80b002f70eed17aa0e/4a20d0f9bcf93769510c61687f77f601fa63a516eeef97450bb6389799ae0520?apiKey=5f631a91ec9b4d80b002f70eed17aa0e&"
                className="object-contain z-10 max-w-full aspect-[1.39] w-[232px]"
                alt="Feature illustration"
              />
              <div className="flex items-start mt-0 max-w-full w-[232px]">
                <div className="shrink-0 w-px border border-solid border-neutral-200 h-[299px]"></div>
                <div className="flex flex-col items-start pb-36 mt-40 bg-white max-md:pb-24 max-md:mt-10">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/5f631a91ec9b4d80b002f70eed17aa0e/75869e186c300239ad580e09216dfffd7f7fe090b2946795d398f86bf75c8886?apiKey=5f631a91ec9b4d80b002f70eed17aa0e&"
                    className="object-contain z-10 -mt-8 w-48 shadow-lg aspect-[1.94]"
                    alt="Feature detail"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <button className="flex overflow-hidden flex-col justify-center items-center self-start px-2 py-1.5 mt-4 text-sm font-medium tracking-wide leading-6 text-sky-500 uppercase rounded">
        <div className="flex gap-2 justify-center items-center">
          <span className="self-stretch my-auto">Watch Demo</span>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/5f631a91ec9b4d80b002f70eed17aa0e/1dd2954a80272dc23964029c696b3bac4a0695dbb9994b2295718e9afb179f73?apiKey=5f631a91ec9b4d80b002f70eed17aa0e&"
            className="object-contain shrink-0 self-stretch my-auto w-4 aspect-[0.67] min-h-[24px]"
            alt=""
          />
        </div>
      </button>
    </section>
  );
}

export default NewFeature;
