/**
 * This code was generated by Builder.io
 */
import React from "react";

function PreviewSection() {
  const previewButtons = [
    { text: "Preview the full Material UI library", bgColor: "bg-sky-500" },
    { text: "Preview the full Joy UI library", bgColor: "bg-fuchsia-700" }
  ];

  return (
    <section className="flex flex-col mt-12 w-full max-md:mt-10 max-md:max-w-full">
      <h2 className="text-4xl tracking-wide leading-none text-black text-opacity-90 max-md:max-w-full">
        Preview the full version
      </h2>
      <div className="flex flex-col mt-4 max-w-full text-base font-medium leading-7 text-white w-[318px]">
        {previewButtons.map((button, index) => (
          <div
            key={index}
            className="flex overflow-hidden flex-col justify-center p-6 w-full bg-white rounded border border-solid border-black border-opacity-10 max-md:px-5 mt-4 first:mt-0"
          >
            <button
              className={`flex overflow-hidden flex-col justify-center items-center px-6 py-2 w-full ${button.bgColor} rounded shadow max-md:px-5`}
            >
              <span className="gap-2 self-stretch">{button.text}</span>
            </button>
          </div>
        ))}
      </div>
    </section>
  );
}

export default PreviewSection;
