/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import MainContent from "./MainContent";
import Footer from "./Footer";

function WelcomePage() {
  return (
    <div className="flex overflow-hidden flex-wrap bg-white">
      <Header />
      <MainContent />
    </div>
  );
}

export default WelcomePage;
