/**
 * This code was generated by Builder.io
 */
import React from "react";

function WelcomeSection() {
  return (
    <section className="flex flex-col mt-12 w-full max-md:mt-10 max-md:max-w-full">
      <h2 className="text-4xl tracking-wide leading-none text-black text-opacity-90 max-md:max-w-full">
        Welcome
      </h2>
      <p className="mt-4 text-base tracking-normal leading-6 text-black text-opacity-60 max-md:max-w-full">
        Thank you for duplicating our community version of the Material UI for
        Figma.
        <br />
        <br />
        In this version, you can freely use the instances to design your
        screens. If you need access to the source components, you can purchase
        the full version which includes the a comprehensive component inventory
        for Figma. It includes over 1,500 unique elements that cover the full
        range of states and variations of each component.
      </p>
    </section>
  );
}

export default WelcomeSection;
