when:
  - branch: [master]
    event: tag

steps:
  - name: Publish docker image to codeberg
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_OWNER}/${CI_REPO}
      dry-run: true
      registry: codeberg.org
      username: docker
      tags:
        - ${CI_COMMIT_TAG##v}
      password:
        from_secret: DOCKER_PASS
      dockerfile: Dockerfile
      platforms: linux/arm64/v8
      auto_tag: true
      labels:
        - version: ${CI_COMMIT_TAG##v}
        - description: "Masters thesis for developing Client web app"
        - author: "Iliyan Kostov"
        - env: "prod"
