name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

    branches:
      - master
    paths:
      - "**"
      - "!.gitignore"
      - "!README.md"

jobs:
  checkout:
    name: Checkout repo
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Save repo to artifact
        uses: actions/upload-artifact@v4
        with:
          name: phd-portal-client
          path: .
          overwrite: true
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: checkout
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: false
      matrix:
        nodejs_version: [20]

    steps:
      - name: Download repo artifact
        uses: actions/download-artifact@v4
        with:
          name: phd-portal-client
          path: .

      - name: Set up NodeJS ${{ matrix.nodejs_version  }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs_version  }}
          check-latest: false

      - name: Test
        run: |
          npm install --legacy-peer-deps
          npm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        nodejs_version: [20]
        eslint_version: [8.56.0]
        prettier_version: [3.3.3]

    permissions:
      checks: write
      contents: write

    steps:
      # BUG: download artifact doesn't grant the linter action permission to view commit history
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up NodeJS ${{ matrix.nodejs_version  }}
        uses: actions/setup-node@v4
        with:
          check-latest: false
          node-version: "${{ matrix.nodejs_version }}"

      - name: Install dependencies
        run: |
          npm install eslint@${{ matrix.eslint_version }} prettier@${{ matrix.prettier_version  }} --save-dev --legacy-peer-deps
          npm install --legacy-peer-deps

      - name: Lint
        uses: wearerequired/lint-action@v2.3.0
        with:
          # FIX: eslint couldn't find configuration file for this project
          # eslint: true
          prettier: true
